bug(tgnms-v2): Fix draft input file upload failing when renaming across partitions
Summary:
# Bug Overview
Encountered an error while trying to upload an input file:
```
Error: EXDEV: cross-device link not permitted, rename '/tmp/anp-uploads/f7f4c6e0f4e6c69009f18df707dd5621' -> '/home/tommylehuynh/connectivity-lab/terragraph/nms/tgnms/fbcnms-projects/tgnms/data/anp/inputs/59-sample-dsm  (1).tif'
```
This is due to trying to rename a file that migrates it across partition boundaries.

# Fix
Use `mv` instead to mv the file and rename it

Reviewed By: aclave1

Differential Revision: D31443879

fbshipit-source-id: ec02a418254987921834a2b066b5a049187efa33