Updates to Scan service to support db schema creation
Summary:
Ran into the following error while creating DB schema:
```
sqlalchemy.exc.CompileError: (in table 'scan_response_rate', column 'network_name'): VARCHAR requires a length on dialect mysql
```
Installed mysql-client to be used by docker-compose to create db user and tables.

Reviewed By: omikader

Differential Revision: D20523158

fbshipit-source-id: 5ebedb9155fabbdd5a13242001a929446d70c7c9