compile Event.thrift in analytics
Summary:
Add Event.thrift to the list of files used by analytics image

Without this change analytics and network_test containers are crashing due to
```
ModuleNotFoundError: No module named 'facebook.gorilla.Event'
```

Reviewed By: csmodlin

Differential Revision: D13509982

fbshipit-source-id: 306b63cd704e983f53956084b93111f704268690