fix(tglib): move shutdown_event creation into coroutine
Summary:
After invoking the PATCH and PUT /config endpoints, tglib apps should shutdown and restart using the newest the config parameters. However, I was noticing that this behavior wasn't working as expected.

```
ERROR 2021-11-12 15:00:56 web.py:451] unhandled exception during asyncio.run() shutdown
task: <Task finished name='Task-1' coro=<_run_app() done, defined at /usr/lib/python3.8/site-packages/aiohttp/web.py:287> exception=RuntimeError("Task <Task pending name='Task-18' coro=<_shutdown_listener() running at /usr/lib/python3.8/site-packages/tglib/main.py:176>> got Fut
ure <Future pending> attached to a different loop")>
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/aiohttp/web.py", line 431, in _run_app
    await asyncio.sleep(delay)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 659, in sleep
    return await future
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/aiohttp/web.py", line 433, in _run_app
    await runner.cleanup()
  File "/usr/lib/python3.8/site-packages/aiohttp/web_runner.py", line 294, in cleanup
    await self._cleanup_server()
  File "/usr/lib/python3.8/site-packages/aiohttp/web_runner.py", line 381, in _cleanup_server
    await self._app.cleanup()
  File "/usr/lib/python3.8/site-packages/aiohttp/web_app.py", line 432, in cleanup
    await self.on_cleanup.send(self)
  File "/usr/lib/python3.8/site-packages/aiosignal/__init__.py", line 36, in send
    await receiver(*args, **kwargs)  # type: ignore
  File "/usr/lib/python3.8/site-packages/tglib/main.py", line 146, in _stop_background_tasks
    await app["shutdown_listener_task"]
  File "/usr/lib/python3.8/site-packages/tglib/main.py", line 176, in _shutdown_listener
    await app["shutdown_event"].wait()
  File "/usr/lib/python3.8/asyncio/locks.py", line 309, in wait
    await fut
RuntimeError: Task <Task pending name='Task-18' coro=<_shutdown_listener() running at /usr/lib/python3.8/site-packages/tglib/main.py:176>> got Future <Future pending> attached to a different loop
ERROR 2021-11-12 15:00:57 consumer.py:333] Unclosed AIOKafkaConsumer
consumer: <aiokafka.consumer.consumer.AIOKafkaConsumer object at 0x7f5c8c921fa0>
```

It seemed like there was an issue with where `asyncio.Event` object is being created. Specifically, the object was being created outside of an `async` function, and before the invocation of `web.run_app`. Under the hood, the [`run_app`](https://github.com/aio-libs/aiohttp/blob/master/aiohttp/web.py#L482) function creates a new loop if one isn't specifically provided.

The fix is to move the creation of the shutdown_event to directly inside the listener instead of outside.

Reviewed By: aclave1

Differential Revision: D32388943

fbshipit-source-id: b8cfb0eb53b74fe96dac5982681ad33c00e14683