Suppress benign mypy ptr errors
Summary:
`ptr` caught the [following errors](https://www.internalfb.com/intern/sandcastle/log/?instance_id=22517998475332392&step_id=22518001271860469&step_index=5&name=Run%20ptr). These errors do not seem to be caused by our services. It's possible that were caused by a new version of `mypy`. Suppressing to unblock CI.

```
Stdout:
-- Summary (total time 36s):
{emoji:2705} PASS: 8
{emoji:274c} FAIL: 3
️{emoji:231b} TIMEOUT: 0
{emoji:1f512} DISABLED: 1
{emoji:1f4a9} TOTAL: 11
-- 11 / 16 (68%) `setup.py`'s have `ptr` tests running
-- Failure Output --
/mnt/btrfs/trunk-hg-connectivity-lab-118890497-1602867536/sandcastle/setup.py (failed 'mypy_run' step):
ci_jobs/nms.py:26: error: Incompatible return value type (got "List[Dict[str, object]]", expected "Dict[str, Any]")
Found 1 error in 1 file (checked 1 source file)
/mnt/btrfs/trunk-hg-connectivity-lab-118890497-1602867536/terragraph/nms/network_health_service/setup.py (failed 'mypy_run' step):
network_health_service/jobs.py:13: note: In module imported here,
network_health_service/main.py:14: note: ... from here:
network_health_service/stats/fetch_stats.py: note: In function "get_link_queries":
network_health_service/stats/fetch_stats.py:25: error: Value of type variable "_LT" of "min" cannot be "Optional[int]"
network_health_service/stats/fetch_stats.py:37: error: Value of type variable "_LT" of "min" cannot be "Optional[int]"
network_health_service/stats/fetch_stats.py:52: error: Value of type variable "_LT" of "min" cannot be "Optional[int]"
network_health_service/stats/fetch_stats.py:60: error: Value of type variable "_LT" of "min" cannot be "Optional[int]"
network_health_service/stats/fetch_stats.py: note: In function "get_node_queries":
network_health_service/stats/fetch_stats.py:118: error: Value of type variable "_LT" of "min" cannot be "Optional[int]"
Found 5 errors in 1 file (checked 1 source file)
/mnt/btrfs/trunk-hg-connectivity-lab-118890497-1602867536/terragraph/nms/topology_service/setup.py (failed 'mypy_run' step):
topology_service/jobs.py:15: note: In module imported here,
topology_service/main.py:17: note: ... from here:
topology_service/utils.py: note: In function "sanitize_topology":
topology_service/utils.py:25: error: Returning Any from function declared to return "_SupportsLessThan"
topology_service/utils.py:26: error: Returning Any from function declared to return "_SupportsLessThan"
topology_service/utils.py:27: error: Returning Any from function declared to return "_SupportsLessThan"
Found 3 errors in 1 file (checked 1 source file)
```

Reviewed By: omikader, driazati

Differential Revision: D24405025

fbshipit-source-id: 9d7cf3ee6235287c3ecbc855faab70a29d176b17