fix(tglib): fix alpine repo version
From oligraw:
"A previous fix f57cac2 allowed mixing between alpine 3.12 and current
'edge'. 'edge' has advanced and is now no longer compatible with 3.12.
Linking fails with 'undefined reference to `std::__throw_bad_array_new_length()`'
likely due to mismatched libc.
Point the repo to 3.14 as was originally intended."