fix(ansible): fix templating issue in udp_pinger docker-compose
Summary:
Ansible was trying to template an environment variable because of a typo where there were two `{` instead of two `$`.

```
AnsibleError: template error while templating string: unexpected '}'.
```

Reviewed By: elludraon

Differential Revision: D22043468

fbshipit-source-id: 247cf7f753ecf3b1c932320c647f4216853782aa