misc(tglib): add pool_recycle arg to MySQL engine constructor
Summary:
Every so often I'll see the following error in the `network_test` logs:

```
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/lib/python3.7/site-packages/network_test/routes.py", line 466, in handle_get_execution
    execution_output = await Scheduler.describe_execution(execution_id)
  File "/usr/lib/python3.7/site-packages/network_test/scheduler.py", line 483, in describe_execution
    cursor = await sa_conn.execute(get_execution_query)
  File "/usr/lib/python3.7/site-packages/aiomysql/sa/connection.py", line 173, in _execute
    await cursor.execute(str(compiled), post_processed_params)
  File "/usr/lib/python3.7/site-packages/aiomysql/cursors.py", line 239, in execute
    await self._query(query)
  File "/usr/lib/python3.7/site-packages/aiomysql/cursors.py", line 457, in _query
    await conn.query(q)
  File "/usr/lib/python3.7/site-packages/aiomysql/connection.py", line 428, in query
    await self._read_query_result(unbuffered=unbuffered)
  File "/usr/lib/python3.7/site-packages/aiomysql/connection.py", line 622, in _read_query_result
    await result.read()
  File "/usr/lib/python3.7/site-packages/aiomysql/connection.py", line 1105, in read
    first_packet = await self.connection._read_packet()
  File "/usr/lib/python3.7/site-packages/aiomysql/connection.py", line 561, in _read_packet
    packet_header = await self._read_bytes(4)
  File "/usr/lib/python3.7/site-packages/aiomysql/connection.py", line 604, in _read_bytes
    raise OperationalError(2013, msg) from e
pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query ([Errno 104] Connection reset by peer)')
```

After doing some digging, it seems like this happens because MySQL is not closing inactive non-interactive connections properly. MySQL server has a [system variable](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_wait_timeout) it uses to determine when to close these kinds of connections, but the default is after 8 hours of inactivity.

`sqlalchemy` offers [two ways](https://docs.sqlalchemy.org/en/13/core/pooling.html#dealing-with-disconnects) to handle disconnects, and though I'd prefer the pessimistic approach that automatically tests every connection with a `SELECT 1` query before executing the intended query, the `pool_pre_ping` argument is unsupported in `aiomysql`.

`aiomysql` does support optimistic disconnect handling through [pool recycling](https://github.com/aio-libs/aiomysql/issues/132), which is a way to force the connection pool to recycle inactive connections after the number of `pool_recycle` seconds has passed, effectively overriding the MySQL server default. It is my understanding that we should no longer see these errors so long as this value is shorter than the `wait_timeout` system variable.

I chose 10 seconds as the default value because it seems like a reasonable upper bound for how long we should allow a connection to live.

Reviewed By: pmccut, aclave1

Differential Revision: D21633829

fbshipit-source-id: f22f401d7049d0785b79076e43fe9537a2ff5a52