fix(ci): use 'run' instead of older 'check_call' subprocess API
Summary:
Seeing `TypeError: __init__() got an unexpected keyword argument 'check'` in the build logs for `weather_service`. The fix is to use the `run` command which supports the `check` kwarg. Besides, the docs suggest using `run` explicitly over the higher level APIs in Python versions >3.5

https://ci.terragraph.link/job/MSA_weather_service/347/console

Reviewed By: driazati

Differential Revision: D24657242

fbshipit-source-id: 4277c29c2881f349c62a711300b9bffbf8ff9e97